language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: i5rl81GkVt8uTjvEuVeuXXj5YZwQ+OGKp4mlFYJrLWZ6MopKbaDu8Z6FxuHRwNtAoz9wzBna/B1STGtmYPNLMBb9jVT/MF49ectKPyTiGwX1yzeO81BiHSkN3Zz5bRQEPtIjSbaMSm3KXRmR+alEFqhdqOymcOTTbNZ6kXrpbonnehXsph64AqwvE5cp+TPC8ZcaeKF9/tWS9rjC6V8VgsoQ7WnA/ti/WCLmiZvqjprIHZuB1QROOlt8dB0xmg/foiSVsJRt3JHHqCy+nHiaZwBD7v2KnT1C4BpWHJ62n4st/drOGidR9YrMVbYZ1BDxnIwuFjC1332OmeMhfX1VtmzyopwGJes7kUGckrS4cMfVsNHEW7yaj4tiMa9vzA7QE2ESXoZIX3FCttbgiM5vtp9KfHzsSF7nX1bgAgBFH3J62R07itV9vmS7WqTADagWZ3DmjJLavcu2irnsNP5ebrT8W8EZxaEzfZJQfX/DYjSUXtEE7UtAw8prjiU1WHwcYIHW96owHk6Yiote86myafT9O3KEsg3Z6jXbGCtQnpoy1EBkoCZGuj11WFIWAIQYlfURxDW8gfJFN4ujEfgsM/wM+4f1reeOJRcXdvaNtUdCjjximvnQYY8WKd1vZQdSMNZ9LcrWjvBpNUA+lwQZgDM3O0QME7sRI416NwMjD/g=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-docker-registry-trigger-plugin
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: dldBcDS/lR+4AVYCWxWZ1g9hohq4npXK4aMBZM1EZod5jeVYNyEeotGKgT4SgxhcQSYKr/z14kAqeH8zo7w/aEC/c86bnI4o5sVQ7AGcRVkEiHuDinBqhxmH+g3WM+mT3UNr8MnfJ37zSqSx4I5rx9C9In3jJ/7fKxT11IKhSDNZ/4DFY+CGgbRnl5gAy7k/XidT0KEACHUjXBDZXMg6SIr7TGXyxFUufhREdtilc4g2RDCBEqP/BBUfRgXlR6QRgYmPwc5yzG5FZA+/P1VLRr2JkAwhrycLWp+3Sf/bKTTHEG2bm4BDzSzb10FwU3wg9eXGiOvjjJ8KLwWi7+IkzyagNbgBi7SEtzrmQgVOtX/2nmvZgEz1b6cGicMFXCo6NXHAFR7IsKQARtHQ8Yos0dXXczXFW0CQkddWrhUDIOq2SyZrgKdsLOWIpJLK62//wpIIr44LIjZcMaO6GbdjkKZ0XYhuKN4vfPpzlninrEEzomud6SV0BVGm0av1n/2tZgyd5zee79aIhFEwNXERdL52mFO6Hd76ayCBNDjM+NMpVAABCvLNHDmp2iXd5VH4AnIKWtoaTs9oaraYfXRSWIyg9CymUws9uQ46K6DPVGGxZYjWgE4e7P6Pql5Fqh8FL14Y9/6dlMnRfBhuLfMGDrlc1pptMmVUxKExMfgmFn8=
